### ISSUE TITLE
Issue When Concourse Triggers Alert - curl error (SSL)

### ISSUE THREAD

**Issue by tman5** [FidelityInternational/concourse-teams-notification-resource#6]
Running into an issue where Concourse will go to trigger an alert and the following is returned:
```
curl: (77) error setting certificate verify locations:

  CAfile: /etc/ssl/certs/ca-certificates.crt
```
Getting into the container that concourse is running and trying to curl any https location results in the same error. 

However, when pulling down the docker image and running it locally, curling https addresses work without issue. Only appears to be a problem when Concourse is using it as a resource

**Comment by jimconner** [comment]
Hi @tman5  - I've checked the config for our own Concourse pipelines and I can't see anywhere that we're pushing an extra certificate into the contianer or anything like that. I wonder if your own concourse is setting an SSL_CERT_FILE environment variable and that's why  curl is trying to find that particular CACert.

**Comment by jimconner** [comment]
Closing issue as there has been no action in the past 8 months.
